export const countryList = [
  { name: "Afghanistan", value: "Afghanistan" },
  { name: "Albania", value: "Albania" },
  { name: "Algeria", value: "Algeria" },
  { name: "Andorra", value: "Andorra" },
  { name: "Angola", value: "Angola" },
  { name: "Antigua and Barbuda", value: "Antigua and Barbuda" },
  { name: "Argentina", value: "Argentina" },
  { name: "Armenia", value: "Armenia" },
  { name: "Australia", value: "Australia" },
  { name: "Austria", value: "Austria" },
  { name: "Azerbaijan", value: "Azerbaijan" },
  { name: "Bahamas", value: "Bahamas" },
  { name: "Bahrain", value: "Bahrain" },
  { name: "Bangladesh", value: "Bangladesh" },
  { name: "Barbados", value: "Barbados" },
  { name: "Belarus", value: "Belarus" },
  { name: "Belgium", value: "Belgium" },
  { name: "Belize", value: "Belize" },
  { name: "Benin", value: "Benin" },
  { name: "Bhutan", value: "Bhutan" },
  { name: "Bolivia", value: "Bolivia" },
  { name: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { name: "Botswana", value: "Botswana" },
  { name: "Brazil", value: "Brazil" },
  { name: "Brunei", value: "Brunei" },
  { name: "Bulgaria", value: "Bulgaria" },
  { name: "Burkina Faso", value: "Burkina Faso" },
  { name: "Burundi", value: "Burundi" },
  { name: "Cambodia", value: "Cambodia" },
  { name: "Cameroon", value: "Cameroon" },
  { name: "Canada", value: "Canada" },
  { name: "Cape Verde", value: "Cape Verde" },
  { name: "Central African Republic", value: "Central African Republic" },
  { name: "Chad", value: "Chad" },
  { name: "Chile", value: "Chile" },
  { name: "China", value: "China" },
  { name: "Colombia", value: "Colombia" },
  { name: "Comoros", value: "Comoros" },
  { name: "Congo (DR)", value: "Congo (DR)" },
  { name: "Costa Rica", value: "Costa Rica" },
  { name: "Croatia", value: "Croatia" },
  { name: "Cuba", value: "Cuba" },
  { name: "Cyprus", value: "Cyprus" },
  { name: "Czech Republic", value: "Czech Republic" },
  { name: "Denmark", value: "Denmark" },
  { name: "Djibouti", value: "Djibouti" },
  { name: "Dominica", value: "Dominica" },
  { name: "Dominican Republic", value: "Dominican Republic" },
  { name: "East Timor", value: "East Timor" },
  { name: "Ecuador", value: "Ecuador" },
  { name: "Egypt", value: "Egypt" },
  { name: "El Salvador", value: "El Salvador" },
  { name: "Equatorial Guinea", value: "Equatorial Guinea" },
  { name: "Eritrea", value: "Eritrea" },
  { name: "Estonia", value: "Estonia" },
  { name: "Eswatini", value: "Eswatini" },
  { name: "Ethiopia", value: "Ethiopia" },
  { name: "Fiji", value: "Fiji" },
  { name: "Finland", value: "Finland" },
  { name: "France", value: "France" },
  { name: "Gabon", value: "Gabon" },
  { name: "Gambia", value: "Gambia" },
  { name: "Georgia", value: "Georgia" },
  { name: "Germany", value: "Germany" },
  { name: "Ghana", value: "Ghana" },
  { name: "Greece", value: "Greece" },
  { name: "Grenada", value: "Grenada" },
  { name: "Guatemala", value: "Guatemala" },
  { name: "Guinea", value: "Guinea" },
  { name: "Guinea-Bissau", value: "Guinea-Bissau" },
  { name: "Guyana", value: "Guyana" },
  { name: "Haiti", value: "Haiti" },
  { name: "Honduras", value: "Honduras" },
  { name: "Hungary", value: "Hungary" },
  { name: "Iceland", value: "Iceland" },
  { name: "India", value: "India" },
  { name: "Indonesia", value: "Indonesia" },
  { name: "Iran", value: "Iran" },
  { name: "Iraq", value: "Iraq" },
  { name: "Ireland", value: "Ireland" },
  { name: "Israel", value: "Israel" },
  { name: "Italy", value: "Italy" },
  { name: "Ivory Coast", value: "Ivory Coast" },
  { name: "Jamaica", value: "Jamaica" },
  { name: "Japan", value: "Japan" },
  { name: "Jordan", value: "Jordan" },
  { name: "Kazakhstan", value: "Kazakhstan" },
  { name: "Kenya", value: "Kenya" },
  { name: "Kiribati", value: "Kiribati" },
  { name: "Korea (North)", value: "Korea (North)" },
  { name: "Korea (South)", value: "Korea (South)" },
  { name: "Kosovo", value: "Kosovo" },
  { name: "Kuwait", value: "Kuwait" },
  { name: "Kyrgyzstan", value: "Kyrgyzstan" },
  { name: "Laos", value: "Laos" },
  { name: "Latvia", value: "Latvia" },
  { name: "Lebanon", value: "Lebanon" },
  { name: "Lesotho", value: "Lesotho" },
  { name: "Liberia", value: "Liberia" },
  { name: "Libya", value: "Libya" },
  { name: "Liechtenstein", value: "Liechtenstein" },
  { name: "Lithuania", value: "Lithuania" },
  { name: "Luxembourg", value: "Luxembourg" },
  { name: "Madagascar", value: "Madagascar" },
  { name: "Malawi", value: "Malawi" },
  { name: "Malaysia", value: "Malaysia" },
  { name: "Maldives", value: "Maldives" },
  { name: "Mali", value: "Mali" },
  { name: "Malta", value: "Malta" },
  { name: "Marshall Islands", value: "Marshall Islands" },
  { name: "Mauritania", value: "Mauritania" },
  { name: "Mauritius", value: "Mauritius" },
  { name: "Mexico", value: "Mexico" },
  { name: "Micronesia", value: "Micronesia" },
  { name: "Moldova", value: "Moldova" },
  { name: "Monaco", value: "Monaco" },
  { name: "Mongolia", value: "Mongolia" },
  { name: "Montenegro", value: "Montenegro" },
  { name: "Morocco", value: "Morocco" },
  { name: "Mozambique", value: "Mozambique" },
  { name: "Myanmar", value: "Myanmar" },
  { name: "Namibia", value: "Namibia" },
  { name: "Nauru", value: "Nauru" },
  { name: "Nepal", value: "Nepal" },
  { name: "Netherlands", value: "Netherlands" },
  { name: "New Zealand", value: "New Zealand" },
  { name: "Nicaragua", value: "Nicaragua" },
  { name: "Niger", value: "Niger" },
  { name: "Nigeria", value: "Nigeria" },
  { name: "North Macedonia", value: "North Macedonia" },
  { name: "Norway", value: "Norway" },
  { name: "Oman", value: "Oman" },
  { name: "Pakistan", value: "Pakistan" },
  { name: "Palau", value: "Palau" },
  { name: "Palestine", value: "Palestine" },
  { name: "Panama", value: "Panama" },
  { name: "Papua New Guinea", value: "Papua New Guinea" },
  { name: "Paraguay", value: "Paraguay" },
  { name: "Peru", value: "Peru" },
  { name: "Philippines", value: "Philippines" },
  { name: "Poland", value: "Poland" },
  { name: "Portugal", value: "Portugal" },
  { name: "Qatar", value: "Qatar" },
  { name: "Romania", value: "Romania" },
  { name: "Russia", value: "Russia" },
  { name: "Rwanda", value: "Rwanda" },
  { name: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
  { name: "Saint Lucia", value: "Saint Lucia" },
  {
    name: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
  },
  { name: "Samoa", value: "Samoa" },
  { name: "San Marino", value: "San Marino" },
  { name: "Sao Tome and Principe", value: "Sao Tome and Principe" },
  { name: "Saudi Arabia", value: "Saudi Arabia" },
  { name: "Senegal", value: "Senegal" },
  { name: "Serbia", value: "Serbia" },
  { name: "Seychelles", value: "Seychelles" },
  { name: "Sierra Leone", value: "Sierra Leone" },
  { name: "Singapore", value: "Singapore" },
  { name: "Slovakia", value: "Slovakia" },
  { name: "Slovenia", value: "Slovenia" },
  { name: "Solomon Islands", value: "Solomon Islands" },
  { name: "Somalia", value: "Somalia" },
  { name: "South Africa", value: "South Africa" },
  { name: "South Sudan", value: "South Sudan" },
  { name: "Spain", value: "Spain" },
  { name: "Sri Lanka", value: "Sri Lanka" },
  { name: "Sudan", value: "Sudan" },
  { name: "Suriname", value: "Suriname" },
  { name: "Sweden", value: "Sweden" },
  { name: "Switzerland", value: "Switzerland" },
  { name: "Syria", value: "Syria" },
  { name: "Tajikistan", value: "Tajikistan" },
  { name: "Tanzania", value: "Tanzania" },
  { name: "Thailand", value: "Thailand" },
  { name: "Togo", value: "Togo" },
  { name: "Tonga", value: "Tonga" },
  { name: "Trinidad and Tobago", value: "Trinidad and Tobago" },
  { name: "Tunisia", value: "Tunisia" },
  { name: "Turkey", value: "Turkey" },
  { name: "Turkmenistan", value: "Turkmenistan" },
  { name: "Tuvalu", value: "Tuvalu" },
  { name: "Uganda", value: "Uganda" },
  { name: "Ukraine", value: "Ukraine" },
  { name: "United Arab Emirates", value: "United Arab Emirates" },
  { name: "United Kingdom", value: "United Kingdom" },
  { name: "United States", value: "United States" },
  { name: "Uruguay", value: "Uruguay" },
  { name: "Uzbekistan", value: "Uzbekistan" },
  { name: "Vanuatu", value: "Vanuatu" },
  { name: "Vatican City", value: "Vatican City" },
  { name: "Venezuela", value: "Venezuela" },
  { name: "Vietnam", value: "Vietnam" },
  { name: "Yemen", value: "Yemen" },
  { name: "Zambia", value: "Zambia" },
  { name: "Zimbabwe", value: "Zimbabwe" },
];

export const Gender = [
  {
    name: "Male",
    value: "male",
  },
  {
    name: "Female",
    value: "female",
  },
  {
    name: "Other",
    value: "other",
  },
];

export const investmentPlans = [
  {
    plan: "Basic",
    interestRate: "10%",
    termDays: 30,
    minDeposit: 1000,
    maxDeposit: 9999,
    capitalReturn: "Each Term",
  },
  {
    plan: "Amateur",
    interestRate: "13%",
    termDays: 30,
    minDeposit: 11000,
    maxDeposit: 24999,
    capitalReturn: "Each Term",
  },
  {
    plan: "Day Trading",
    interestRate: "14%",
    termDays: 30,
    minDeposit: 25000,
    maxDeposit: 25000,
    capitalReturn: "Each Term",
  },
  {
    plan: "Standard",
    interestRate: "15%",
    termDays: 30,
    minDeposit: 25000,
    maxDeposit: 70000,
    capitalReturn: "Each Term",
  },
  {
    plan: "Legacy",
    interestRate: "17%",
    termDays: 30,
    minDeposit: 71000,
    maxDeposit: 140000,
    capitalReturn: "Each Term",
  },
];

export const traders = [
  {
    TraderDetails: "4356712 | Young bull investor",
    ROI: "10%",
    Accuracy: "97%",
    TotalProfit: "108,900",
    Copiers: 208,
    MinFee: 10000,
    Days: 28,
    StandaloneNumber: "4356712",
  },
  {
    TraderDetails: "9694814 | Sean Trades",
    ROI: "11%",
    Accuracy: "98%",
    TotalProfit: "10,895,785",
    Copiers: 607,
    MinFee: 7000,
    Days: 28,
    StandaloneNumber: "9694814",
  },
  {
    TraderDetails: "3182915 | Sniper Trades",
    ROI: "8%",
    Accuracy: "95%",
    TotalProfit: "458,608",
    Copiers: 308,
    MinFee: 1000,
    Days: 40,
    StandaloneNumber: "3182915",
  },
  {
    TraderDetails: "4447716 | Mamba FX",
    ROI: "10%",
    Accuracy: "97%",
    TotalProfit: "506,078",
    Copiers: 109,
    MinFee: 8000,
    Days: 28,
    StandaloneNumber: "4447716",
  },
  {
    TraderDetails: "7491017 | Panda Options",
    ROI: "9%",
    Accuracy: "99%",
    TotalProfit: "458,769",
    Copiers: 678,
    MinFee: 3000,
    Days: 14,
    StandaloneNumber: "7491017",
  },
  {
    TraderDetails: "7563418 | Chris Walker (DCG)",
    ROI: "13%",
    Accuracy: "97%",
    TotalProfit: "321,000",
    Copiers: 145,
    MinFee: 7000,
    Days: 14,
    StandaloneNumber: "7563418",
  },
  {
    TraderDetails: "4187519 | TradeKing",
    ROI: "9%",
    Accuracy: "98%",
    TotalProfit: "321,000",
    Copiers: 198,
    MinFee: 5000,
    Days: 28,
    StandaloneNumber: "4187519",
  },
  {
    TraderDetails: "7908920 | Crypto Expert MC",
    ROI: "12%",
    Accuracy: "98%",
    TotalProfit: "432,550",
    Copiers: 321,
    MinFee: 5000,
    Days: 60,
    StandaloneNumber: "7908920",
  },
  {
    TraderDetails: "4066221 | Alpha Trader",
    ROI: "8%",
    Accuracy: "98%",
    TotalProfit: "435,770",
    Copiers: 205,
    MinFee: 25000,
    Days: 60,
    StandaloneNumber: "4066221",
  },
  {
    TraderDetails: "6661122 | Market Watchers",
    ROI: "12%",
    Accuracy: "98%",
    TotalProfit: "605,200",
    Copiers: 209,
    MinFee: 15000,
    Days: 60,
    StandaloneNumber: "6661122",
  },
  {
    TraderDetails: "4958723 | Alpha Trader",
    ROI: "13%",
    Accuracy: "98%",
    TotalProfit: "321,790",
    Copiers: 108,
    MinFee: 5000,
    Days: 90,
    StandaloneNumber: "4958723",
  },
  {
    TraderDetails: "8397824 | Daniel Green",
    ROI: "9%",
    Accuracy: "97%",
    TotalProfit: "87,100",
    Copiers: 287,
    MinFee: 200,
    Days: 60,
    StandaloneNumber: "8397824",
  },
  {
    TraderDetails: "5313825 | InvestwithZach",
    ROI: "12%",
    Accuracy: "97%",
    TotalProfit: "128,000",
    Copiers: 98,
    MinFee: 4000,
    Days: 60,
    StandaloneNumber: "5313825",
  },
  {
    TraderDetails: "9388326 | Luca DeVries",
    ROI: "12%",
    Accuracy: "98%",
    TotalProfit: "109,805",
    Copiers: 107,
    MinFee: 5200,
    Days: 60,
    StandaloneNumber: "9388326",
  },
  {
    TraderDetails: "5249427 | Mr. Rich",
    ROI: "13%",
    Accuracy: "97%",
    TotalProfit: "706,700",
    Copiers: 304,
    MinFee: 10000,
    Days: 60,
    StandaloneNumber: "5249427",
  },
  {
    TraderDetails: "9943828 | CryptoDude",
    ROI: "8%",
    Accuracy: "98%",
    TotalProfit: "320,890",
    Copiers: 132,
    MinFee: 2000,
    Days: 60,
    StandaloneNumber: "9943828",
  },
  {
    TraderDetails: "8579630 | Max Pro",
    ROI: "14%",
    Accuracy: "98%",
    TotalProfit: "201,980",
    Copiers: 203,
    MinFee: 15000,
    Days: 60,
    StandaloneNumber: "8579630",
  },
  {
    TraderDetails: "5117131 | Clear Path",
    ROI: "11%",
    Accuracy: "97%",
    TotalProfit: "209,789",
    Copiers: 204,
    MinFee: 3000,
    Days: 60,
    StandaloneNumber: "5117131",
  },
  {
    TraderDetails: "9684233 | Dr. Mark",
    ROI: "13%",
    Accuracy: "98%",
    TotalProfit: "325,000",
    Copiers: 207,
    MinFee: 7000,
    Days: 60,
    StandaloneNumber: "9684233",
  },
  {
    TraderDetails: "9216434 | Jacob Ford",
    ROI: "12%",
    Accuracy: "98%",
    TotalProfit: "326,000",
    Copiers: 138,
    MinFee: 5000,
    Days: 60,
    StandaloneNumber: "9216434",
  },
  {
    TraderDetails: "7503735 | The Trade Boss",
    ROI: "15%",
    Accuracy: "97%",
    TotalProfit: "341,000",
    Copiers: 201,
    MinFee: 5000,
    Days: 60,
    StandaloneNumber: "7503735",
  },
];

export const wallets = [
  {
    name: "Bitcoin",
    value: "Bitcoin",
  },
  {
    name: "Ethereum",
    value: "Ethereum",
  },
  {
    name: "USDT(ERC20)",
    value: "USDT(ERC20)",
  },
  {
    name: "USDT(TRC20)",
    value: "USDT(TRC20)",
  },
  {
    name: "SOL",
    value: "SOL",
  },
  {
    name: "XRP",
    value: "XRP",
  },
];

export const trxStatus = [
  {
    name: "Failed",
    value: "failed",
  },
  {
    name: "Pending",
    value: "pending",
  },
  {
    name: "Reverse",
    value: "reverse",
  },
  {
    name: "Successful",
    value: "successful",
  },
];
